name: Restrict direct merge from develop to main

on:
  pull_request:
    branches:
      - main

jobs:
  restrict-develop-merge:
    runs-on: ubuntu-latest

    steps:
      - name: Check if the PR is from develop branch
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" == "develop" ]]; then
            echo "Merging develop branch directly into main is not allowed."
            exit 1
          fi
